from . import Answer1
from . import Answer2
from . import Answer3
from . import Answer4
from . import Answer5
from . import Answer6
from . import Answer7
from . import create_buttons
from . import hello
from . import prise
from . import register
from . import schechik